apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: k8s-kitops
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/mergwyn/k8s-gitops-refactor.git
      revision: HEAD
      directories:
      - path: apps/*/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/mergwyn/k8s-gitops-refactor.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path[1]}}'
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: false
        syncOptions:
        - ServerSideApply=true
        - CreateNamespace=true
        - RespectIgnoreDifferences=true
      ignoreDifferences:
      - group: apps
        kind: GpuDevicePlugin
        jsonPointers:
        - /spec/resourceManager

