apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: k8s-kitops-refactor
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/mergwyn/k8s-gitops-refactor.git
      revision: HEAD
      directories:
      - path: apps/*/*
      - path: apps/node-feature-discovery/*
        exclude: true
#      - path: apps/kube-system/kube-vip-cloud-provider
#        exclude: true
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: "my-project"
      source:
        repoURL: https://github.com/argoproj/argo-cd.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
      
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/mergwyn/k8s-gitops-refactor.git
        targetRevision: HEAD
        path: '{{path}}'
#        kustomize:
#          namespace: '{{path[1]}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path[1]}}'
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: false
        syncOptions:
        - ServerSideApply=true
        - CreateNamespace=true
        - RespectIgnoreDifferences=true
      ignoreDifferences:
      - group: apps
        kind: GpuDevicePlugin
        jsonPointers:
        - /spec/resourceManager

