apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-90"

helmCharts:
- name: argo-cd
  releaseName: argo-cd
  version: 5.49.0
  repo: https://argoproj.github.io/argo-helm
  valuesFile: values.yaml


