apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-83"

helmCharts:
- name: kube-vip-cloud-provider
  releaseName: kube-vip-cloud-provider
  version: 0.2.2
  repo: https://kube-vip.github.io/helm-charts
  #valuesFile: values.yaml

resources:
- configmap.yaml

