apiVersion: v2
name: prowlarr
description: Helm chart for prowlarr
type: application
version: 0.1.0
appVersion: "1.0"


dependencies:
  - name: prowlarr
    repository: https://geek-cookbook.github.io/charts/
    version: 4.5.2
