apiVersion: v2
name: sonarr
description: Helm chart for sonarr
type: application
version: 0.1.0
appVersion: "1.0"


dependencies:
  - name: sonarr
    repository: https://geek-cookbook.github.io/charts/
    version: 16.3.2
